Feature/symfony 4
dayspring-tech/LoginBundle pull request #5
Opened 2021-04-16 20:52 UTC by ssitu-dayspring

2021-04-16 20:56 UTC, ssitu-dayspring commented
Wait to merge after updating propel/propel-bundle version to 1.7

2021-04-19 03:40 UTC, jwong-dayspring requested changes

2021-04-19 03:40 UTC, jwong-dayspring commented on composer.json
> +            "url":  "git@github.com:dayspring-tech/PropelBundle.git"
@ssitu-dayspring It looks like Travis is failing when trying to clone this. I wonder if using `https://github.com/dayspring-tech/PropelBundle` instead would fix it. Composer looks like git@ URLs are meant to be for private repos.
https://getcomposer.org/doc/05-repositories.md#vcs

2021-04-22 21:19 UTC, jwong-dayspring approved these changes

2021-04-22 21:20 UTC, merged